### ISSUE TITLE
Position issues

### ISSUE THREAD

**Issue by Prenden** [cryptol0g1c/solfarm-leveragedpools#1]
Hello

I have found an issue after fetching the issues with the latest version
<img width="1738" alt="Screenshot 2021-12-03 at 11 16 04" src="https://user-images.githubusercontent.com/22123409/144586079-108f03ba-33e2-4aa5-a004-91727af8fa1b.png">
This is my opened position and the software returns the values below:
```
Reserve0: ATLAS price: 0.169158 USD
Reserve1: USDC price: 1 USD
User Key H5WK8gBgjRzdvRuC6tdoNRNjrfnxrmifjgxiAmShagmn
Pair ATLAS-USDC
Borrowed: 2.11725931 USDC
Position Value: 29120.745 USD
Debt Value: 2.117 USD
Equity Value: 29118.628 USD
```

Can you help me to get this and resolve the issue?

**Comment by maxidev** [comment]
Closing, fixed on: https://github.com/cryptol0g1c/solfarm-leveragedpools/releases/tag/v0.0.4
